import 'dart:async';

import 'package:firebase_core/firebase_core.dart';
import 'package:firebase_messaging/firebase_messaging.dart';
import 'package:flutter/foundation.dart';
import 'package:flutter/widgets.dart';

import '../core/config/env.dart';
import '../core/monitoring/analytics_service.dart';
import '../core/monitoring/firebase_analytics_service.dart';
import '../core/monitoring/monitoring_service.dart';
import '../core/push/push_notification_service.dart';
import '../firebase_options.dart';
import 'di.dart';

/// Boots the app inside a guarded zone with Firebase, crash reporting, and
/// analytics wired up before `runApp`.
///
/// Flow:
///   1. `Firebase.initializeApp` with the generated platform options.
///   2. Register the FCM background isolate handler (top-level function).
///   3. Route Flutter framework + platform (async) errors to Crashlytics.
///   4. `configureDependencies` (get_it), then init monitoring/analytics/push.
///   5. `runApp(await builder())` inside `runZonedGuarded`.
///
/// [firebase_options.dart] is generated by `flutterfire configure`; run it
/// before the first build (see docs/).
Future<void> bootstrap(FutureOr<Widget> Function() builder) async {
  await runZonedGuarded<Future<void>>(
    () async {
      WidgetsFlutterBinding.ensureInitialized();

      // The `staging` Android flavor has no app registered in the Firebase
      // project yet, so it skips init entirely rather than crashing on it.
      if (Env.isFirebaseEnabled) {
        await Firebase.initializeApp(
          options: DefaultFirebaseOptions.currentPlatform,
        );

        // Must be registered before runApp so terminated-state pushes are handled.
        FirebaseMessaging.onBackgroundMessage(
          firebaseMessagingBackgroundHandler,
        );
      }

      configureDependencies();

      final monitoring = getIt<MonitoringService>();
      final analytics = getIt<AnalyticsService>();

      if (Env.isFirebaseEnabled) {
        await monitoring.init();
        if (analytics is FirebaseAnalyticsService) {
          await analytics.init();
        }
      }

      // Framework (synchronous build/layout/paint) errors → Crashlytics.
      final previousOnError = FlutterError.onError;
      FlutterError.onError = (details) {
        previousOnError?.call(details);
        monitoring.recordFlutterError(
          FlutterErrorDetailsLike(
            exception: details.exception,
            stack: details.stack,
            context: details.context?.toStringDeep(),
          ),
        );
      };

      // Uncaught async errors outside the Flutter callstack → Crashlytics.
      PlatformDispatcher.instance.onError = (error, stack) {
        monitoring.recordError(error, stack, fatal: true);
        return true;
      };

      // Best-effort push setup; failures must not block app start. Skipped
      // entirely when Firebase is disabled (no FCM without Firebase.initializeApp).
      if (Env.isFirebaseEnabled) {
        unawaited(getIt<PushNotificationService>().init());
      }

      runApp(await builder());
    },
    (error, stack) {
      // Anything the zone catches that escaped the handlers above.
      if (kDebugMode) {
        debugPrint('Uncaught zone error: $error\n$stack');
      }
      getIt<MonitoringService>().recordError(error, stack, fatal: true);
    },
  );
}
