// PLACEHOLDER — replace by running `flutterfire configure`.
//
// This file is normally generated by the FlutterFire CLI and contains the real
// Firebase project keys for each platform. Until `flutterfire configure` is run
// (see docs/), this placeholder keeps the project compiling but throws at
// runtime so a misconfigured build fails loudly instead of silently.
//
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for the current platform.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web. '
        'Run `flutterfire configure` to generate firebase_options.dart.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
      case TargetPlatform.iOS:
      case TargetPlatform.macOS:
      case TargetPlatform.windows:
      case TargetPlatform.linux:
      case TargetPlatform.fuchsia:
        throw UnsupportedError(
          'Firebase is not configured yet. Run `flutterfire configure` to '
          'generate lib/firebase_options.dart with your project keys.',
        );
    }
  }
}
